version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `development` branch
    target-branch: "development"
    # Labels on pull requests for version updates only
    labels:
      - "bundler dependencies"

  - package-ecosystem: "yarn"
    target-branch: "development"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"